import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { runSafe } from "./exec.js";
import { execCmd } from "./docker.js";

const ENV_FILE = ".devcontainer/.env";
const CADDYFILE_PATH = ".openharness/Caddyfile";

const RESERVED_ROUTE_NAMES = new Set(["admin", "www", "gateway", "api-internal"]);
const ROUTE_NAME_RE = /^[a-z][a-z0-9-]{0,30}$/;

export type Mode = "local" | "remote";

export interface GatewayMode {
  mode: Mode;
  publicDomain?: string;
  acmeEmail?: string;
}

export interface Route {
  name: string;
  port: number;
  sandbox: string;
}

function readEnvVar(envPath: string, key: string): string | undefined {
  if (!existsSync(envPath)) return undefined;
  try {
    const content = readFileSync(envPath, "utf-8");
    const match = content.match(new RegExp(`^${key}=(.+)$`, "m"));
    return match?.[1]?.trim() || undefined;
  } catch {
    return undefined;
  }
}

export function detectMode(): GatewayMode {
  const publicDomain = process.env.PUBLIC_DOMAIN ?? readEnvVar(resolve(ENV_FILE), "PUBLIC_DOMAIN");
  const acmeEmail = process.env.ACME_EMAIL ?? readEnvVar(resolve(ENV_FILE), "ACME_EMAIL");

  return publicDomain ? { mode: "remote", publicDomain, acmeEmail } : { mode: "local" };
}

export function validateRouteName(name: string): void {
  if (!ROUTE_NAME_RE.test(name)) {
    throw new Error(`Invalid route name '${name}'. Must match /^[a-z][a-z0-9-]{0,30}$/.`);
  }
  if (RESERVED_ROUTE_NAMES.has(name)) {
    throw new Error(
      `Route name '${name}' is reserved. Reserved: ${[...RESERVED_ROUTE_NAMES].join(", ")}.`,
    );
  }
}

export function hostFor(route: Route, mode: GatewayMode): string {
  const base = `${route.name}.${route.sandbox}`;
  if (mode.mode === "remote") {
    if (!mode.publicDomain) {
      throw new Error("Remote mode requires publicDomain.");
    }
    return `${base}.${mode.publicDomain}`;
  }
  return `${base}.localhost`;
}

export function renderCaddyfile(routes: Route[], mode: GatewayMode): string {
  const lines: string[] = [];

  lines.push("# Generated by `openharness expose` — do not hand-edit.");
  lines.push("{");
  lines.push("  admin 0.0.0.0:2019");
  if (mode.mode === "remote") {
    if (mode.acmeEmail) lines.push(`  email ${mode.acmeEmail}`);
  } else {
    lines.push("  auto_https disable_redirects");
  }
  lines.push("}");
  lines.push("");

  for (const route of routes) {
    const host = hostFor(route, mode);
    const suffix = mode.mode === "remote" ? "" : ":443";
    lines.push(`${host}${suffix} {`);
    if (mode.mode === "local") {
      lines.push("  tls internal");
    }
    lines.push(`  reverse_proxy ${route.sandbox}:${route.port}`);
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

export function writeCaddyfile(content: string): void {
  const path = resolve(CADDYFILE_PATH);
  mkdirSync(dirname(path), { recursive: true });
  const tmp = `${path}.tmp`;
  writeFileSync(tmp, content, "utf-8");
  renameSync(tmp, path);
}

/**
 * Reload Caddy configuration. The Caddyfile is bind-mounted into the gateway
 * container at /etc/caddy/Caddyfile, so we just ask Caddy to reload from disk.
 * Atomic in-process swap — no dropped connections.
 */
export function reloadCaddy(sandboxName: string): boolean {
  const gatewayName = `${sandboxName}-gateway`;
  return runSafe(execCmd(gatewayName, ["caddy", "reload", "--config", "/etc/caddy/Caddyfile"]), {
    stdio: "pipe",
  });
}

/**
 * HEAD-probe a URL to check liveness. Accepts self-signed certs so that
 * local-mode `tls internal` routes are probeable. Returns within `timeoutMs`.
 */
export async function httpProbe(
  url: string,
  timeoutMs = 2000,
): Promise<{ ok: boolean; status?: number }> {
  const isHttps = url.startsWith("https:");
  const mod = isHttps ? await import("node:https") : await import("node:http");

  return new Promise((resolvePromise) => {
    const opts: Record<string, unknown> = { method: "HEAD" };
    if (isHttps) opts.rejectUnauthorized = false;

    const req = mod.request(url, opts as never, (res) => {
      clearTimeout(timer);
      const status = res.statusCode ?? 0;
      resolvePromise({ ok: status > 0 && status < 500, status });
      res.resume();
    });
    const timer = setTimeout(() => {
      req.destroy();
      resolvePromise({ ok: false });
    }, timeoutMs);
    req.on("error", () => {
      clearTimeout(timer);
      resolvePromise({ ok: false });
    });
    req.end();
  });
}
